version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./packages/backend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/comment-system
      - PORT=3001
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data: